# crop.lua
# ==========
# start cropping
c script-message-to crop start-crop hard
alt+c script-message-to crop start-crop soft
# delogo mode can be used like so
l script-message-to crop start-crop delogo
# remove the crop
d vf del -1

# or use the ready-made "toggle" binding
C script-message-to crop toggle-crop hard

# remove the soft zoom
0 set video-pan-x 0; set video-pan-y 0; set video-zoom 0

# encode.lua
# ============
# use default profile (makes vp8 webms)
e script-message-to encode set-timestamp

# use custom webm profile, the argument name must correspond to an existing .conf file (see script-opts/)
alt+e script-message-to encode set-timestamp encode_webm

# use custom profile
E script-message-to encode set-timestamp encode_slice

# blur-edges.lua
# ================
b script-message-to blur_edges toggle-blur

# seek-to.lua
# =============
t script-message-to seek_to toggle-seeker

# seek
b seek -3
g seek 5

RIGHT seek 3 
LEFT seek -3
UP add volume 5
DOWN add volume -5
SHIFT_LEFT seek -1 exact
SHIFT_RIGHT seek 1 exact
Ctrl+LEFT seek -0.1 exact
Ctrl+RIGHT seek 0.1 exact
Ctrl+Shift+LEFT  seek -0.03 exact 
Ctrl+Shift+RIGHT  seek 0.03 exact

# Cycle through subtitle tracks
cycle-values sub-visibility "yes" "auto" "no"
B script-binding sub-cycle

