#screenshot-directory = ~/pictures/mpv
#--"screenshot-template = %F-%p-mpv-shot%[#][0X]n"
screenshot-template="~/pictures/mpv/%{media-title}_%p_mpv-shot%03n"
volume=50
script-opts=encode=set-timespamt,~/.config/mpv/scripts/encode_slice


