# Hyprland configuration

##########################
# General Settings
##########################
general {
    # Font for window titles and bar
    font = pango:hermit 14

    # Window border settings
    border_width = 2
    new_window_border = 1
    new_window_float = 1
    smart_gaps = true

    # Default gap sizes
    gap_inner = 8
    gap_outer = 2
    hide_edge_borders = smart
    border_radius = 0
}

##########################
# Output (Monitor) Configuration
##########################
output DP-0 {
    primary = true
    mode = 2560x1440
    position = 0x0
    rotation = normal
}

output HDMI-0 {
    mode = 1920x1080
    position = 2560x0
    off = true
}

##########################
# Autostart Applications
##########################
exec-once = picom
exec-once = nm-tray
exec-once = feh --bg-fill /home/merulox/pictures/wallpapers/black.jpg
exec-once = alacritty -e xset r rate 300 25
exec-once = fcitx5
exec-once = psi-plus
exec-once = anki
exec-once = proton-pass
exec-once = clipmenud
exec-once = element-desktop
exec-once = spotify
exec-once = org.nicotine_plus.Nicotine
exec-once = obsidian
exec-once = io.github.hydrusnetwork.hydrus

##########################
# Keybindings
##########################

# Define the modifier key as MOD4 (Super key)
bind = MOD4+Shift+Return exec alacritty
bind = MOD4+Return exec alacritty
bind = MOD4+Shift+Ctrl+R reload
bind = MOD4+Shift+C kill
bind = MOD4+Ctrl+Left focus left
bind = MOD4+Ctrl+Right focus right
bind = MOD4+Ctrl+Up focus up
bind = MOD4+Ctrl+Down focus down
bind = MOD4+Shift+Space toggle_floating

# Window resizing
bind = MOD4+Shift+Left resize shrink width 10px
bind

